# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI_tests

on:
  pull_request:
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install system packages
      run: |
          sudo apt update
          sudo apt install libudunits2-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: |
        tox

  minimal-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create virtual env
        run: python3 -m venv venv --upgrade-deps
      - name: Install pyaro
        run: source venv/bin/activate && pip install ./
      - name: Try importing pyaro
        run: source venv/bin/activate && python -c "import pyaro; print(pyaro.__version__)"
    
